title: Hello, world! I'm Sambhav Dusad
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Sambhav Dusad # add your name
author-img: sambhav.jpg # add your photo
about-author: # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: dsam82 # add your Github handle
social-linkedin: samd82 # add your Linkedin handle
social-email: sambhavdusad24@gmail.com # add your Email address

# Disqus
discus-identifier:

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
